downside to mitigate is if stocks plummet with low fluctuations then money is stuck in stock til market comes back up

In [1]:
import sys
sys.path

['/Users/mitty/Documents/data_science/springboard/project_env/projects/trade/stocks',
 '/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',
 '/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
 '/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',
 '',
 '/usr/local/lib/python3.9/site-packages',
 '/usr/local/lib/python3.9/site-packages/IPython/extensions',
 '/Users/mitty/.ipython']

In [1]:
#time to import what we need
import pandas as pd
import numpy as np
from datetime import date
from datetime import datetime

import seaborn as sns
import matplotlib.pyplot as plt

from client import client
import config

from td.client import TDClient

In [ ]:
client.login()

In [3]:
#API KEY
CONSUMER_KEY = 'CAOWN5GWEGDOMLITROVBPQS6IE9OBCQT'

#redirect URI
REDIRECT_URI = 'https://localhost/test'

#initialize a session
TDSession = TDClient(
    client_id=config.API_KEY,
    redirect_uri=config.REDIRECT_URI
)

#login using api key, redirect and session
TDSession.login()

days = 10

TypeError: expected str, bytes or os.PathLike object, not NoneType

In [8]:
sp500 = ["ATVI", "CMCSA", "LUMN", "DIS", "EA", "IPG", "NFLX", "T", "VZ", "DISCA", "VIAC", "DISCK", "FB", "TWTR", "FOXA", "BBY", "CCL", "TPR", "DHI", "EBAY", "GPS", "HD", "LEN", "LOW", "LB","LVS", "NKE", "PHM", "RCL", "SBUX", "TJX", "WYNN", "MGM", "UAA", "HBI", "ULTA", "MDLZ", "KO", "KR", "MO", "PG", "SYY", "WBA", "WMT", "PM", "KHC", "APA", "BKR", "COG", "COP", "CVX", "DVN", "EOG", "FTI", "HAL", "NOV", "OKE", "OXY", "PXD", "SLB", "VLO", "WMB", "XOM", "HFC", "CXO", "KMI", "MPC", "PSX", "FANG", "AFL", "AIG", "IVZ", "AXP", "BAC", "TFC", "BK", "BRK.B", "C", "FITB", "GS", "HBAN", "JPM", "KEY", "MET", "SPGI", "MS", "RF", "SCHW", "USB", "WFC", "ZION", "ABT", "BDX", "BMY", "BSX", "CVS", "DHR", "GILD", "JNJ", "LLY", "MDT", "MRK", "VTRS", "PFE", "UNH", "ABBV", "HWM", "ALK", "BA", "CAT", "EMR", "FAST", "GE", "LUV", "JCI", "UPS", "RTX", "UAL", "DAL", "NLSN", "AAL", "INFO", "FTV", "AAPL", "ADBE", "ADI", "AMAT", "AMD", "CRM", "DXC", "FISV", "GLW", "HPQ", "IBM", "INTC", "JNPR", "MSFT", "MU", "NVDA", "ORCL", "QCOM", "STX", "NLOK", "TXN", "WDC", "CSCO", "WU", "V", "PYPL", "HPE", "FCX", "IP", "MOS", "NEM", "DD", "LIN", "DOW", "CTVA", "AMCR", "AMT", "PEAK", "HST", "IRM", "KIM", "SPG", "WY", "AES", "CNP", "D", "DUK", "FE", "NEE", "PPL", "CARR"]
len(sp500)
symbols = sp500[0:50]
# deleted - amzn, mcd, GM, cl, ua, nclh, cost



symbols = ["A", "HWM", "AAP", "AAPL", "ABC", "ABMD", "CB", "ACN", "ADBE", "ADI", "ADM", "ADP", "ADSK", "AEP", "AES", "AFL", "HES", "AIG", "AIV", "AKAM", "ALB", "ALGN", "ALK", "ALL", "AMAT", "AMD", "AMGN", "AMZN", "ANSS", "AON", "APA", "APD", "APH", "ARE", "ATO", "ATVI", "AVB", "AVY", "IVZ", "AXP", "AZO", "BA", "BAC", "BAX", "TFC", "BDX", "BEN", "WRB", "BKR", "BK", "BLK", "BMY", "BRK.B", "BSX", "BWA", "BXP", "C", "CAH", "CAT", "CBRE", "CCL", "CDNS", "CERN", "FIS", "CI", "CINF", "CMA", "CMCSA", "CME", "CNC", "COF", "TPR", "COO", "COP", "DXC", "LUMN", "CTSH", "CTXS", "CVS", "CVX", "DIS", "DISH", "DLTR", "DRI", "DVN", "EBAY", "ECL", "EL", "EMN", "EMR", "EOG", "EQR", "EA", "ETN", "EW", "EXPD", "EXR", "F", "FAST", "FCX"]

In [ ]:
c = pd.DataFrame({})
sym_dict = []


for i,symbol in enumerate(symbols):
    data = TDSession.get_price_history(symbol, period_type='day', period=str(days), frequency_type='minute', frequency='1')
# df = pd.DataFrame(data)
#     print(data)

    ticker = data['symbol']
    ticker

    data

    test = pd.DataFrame(data['candles'])
    test['time'] = test.apply(lambda row: datetime.fromtimestamp(row.datetime/1000).strftime("%I:%M:%S"),axis=1 )
    test['day'] = test.apply(lambda row: datetime.fromtimestamp(row.datetime/1000).strftime("%d"),axis=1 )
    test['month'] = test.apply(lambda row: datetime.fromtimestamp(row.datetime/1000).strftime("%B"),axis=1 )
    test['year'] = test.apply(lambda row: datetime.fromtimestamp(row.datetime/1000).strftime("%Y"),axis=1 )
    #create open to high column
    test['open_high'] = test['high']-test['open']
    #create open to low column
    test['open_low'] = test['open']-test['low']
    test

    # find a trigger
    # 	significant open to high difference for the minute 
    # 	  	&&
    # 	open to high diff is greater than open to low diff by 120% 
    #         and the open to low is not <1
    # 	significant volume for the past day (90th percentile)
    # 	put buy order in for the trigger open price - only a 6 min window to buy
    #     5% below 6 month high
    #     don't buy within first 15 min of market or last 2 hours
    #     if no 0.5% increase - DO WHAT?
    #    	sell 0.5% increase
    # 	repeat

    # get the data after the trigger
    # return how many minutes it took for 0.5% roi

    #define variables
    candle_diff = 1.2
    morn15 = ['08:{}:00'.format(30+x) for x in range(0,15)]

    
    # recent low mean
    recent_low_mean = test.iloc[-600:,2].mean()

    # past high mean
    past_high_mean = test.iloc[0:600,1].mean()

    
    #define open higher than open low
    high_not_zero = test['open_high'] != 0 
    low_not_zero = test['open_low'] != 0 
    tall_candle = test['open_high'] > candle_diff*test['open_low']
    volume75 = test['volume'] >= np.percentile(test['volume'],[90])[0]
    not_first15 = ~test['time'].isin(morn15)
    price65th = test['open']<np.percentile(test['high'],[65])[0]
    down_trend = past_high_mean < recent_low_mean * 1.02
    price35th = test['open']>np.percentile(test['high'],[45])[0]

    condition = high_not_zero & low_not_zero & tall_candle & volume75 & not_first15 & price65th # & price35th & down_trend

    #checking for trigger of open to high difference bigger than open to low differnce
    trigger_df = test.loc[condition, :].reset_index()
    trigger_df.head()

    
    my_profit = 1.0002
    #add column of desired sell prices
    #desired roi is 0.5%
    trigger_df['to_sell_price'] = trigger_df.open * my_profit
    trigger_df

    #1 min = 60000ms
    def mins_to_ms(mins):
        return mins*60000

    #function to get the period desired
    def get_period(mins, time, df):
        start = df['datetime']>time
        end = df['datetime']<=(time+mins_to_ms(mins))
        return df.loc[start&end,['datetime','low']]

    #loop through low price of period to check for sell
    def did_sell(df_period, sell_price,i):
        return [row1 if row1 >= sell_price else False for row1 in df_period]

    #if pd.DataFrame(row1).iloc[0,:][ind].low[0] >= sell_price else False

    #loop through low price of period to check for sell
    def did_buy(df_period, buy_price,i):
        return [row1 if row1 <= buy_price else False for row1 in df_period]



    #def did_sell(df_period, sell_price,i):
    #    return [(row1,i[0]) if row1 >= sell_price else False for index,row1 in enumerate(df_period)]

    test.loc[:,['datetime','low']].iloc[0,:].low

    ## Bought

    #the time period that you want to get after the trigger
    time_period6 = [get_period(6, row[6], test) for i,row in trigger_df.iterrows()]

    #did we buy???
    trigger_df['bought'] = pd.DataFrame([did_buy(time_period6[i].low,row[1],i) for i,row in trigger_df.iterrows()]).any(axis=1)
    #trigger_df

    ## Sold

    #the time period that you want to get after the trigger
    time_period20 = [get_period(14400, (row[6]+60000), test) for i,row in trigger_df.iterrows()]

    #did we sell???
    sold = pd.DataFrame([did_sell(time_period20[i].low,row[13],time_period20[i].datetime) for i,row in trigger_df.iterrows()])
    #sold_time = [did_sell(time_period20[i].low,row[13],time_period20[i].datetime) for i,row in trigger_df.iterrows()][0][1]
    trigger_df['sold'] = pd.DataFrame(sold).any(axis=1)

    #trigger_df['sold'].sum()
    #trigger_df.loc[trigger_df['sold']==False,:]
    #trigger_df
    sold

    # sold = pd.DataFrame([did_sell(time_period20[i].low,row[13],time_period20[i].datetime) for i,row in trigger_df.iterrows()])
    # sold_time = [did_sell(time_period20[i].low,row[13],time_period20[i].datetime) for i,row in trigger_df.iterrows()][0][1]

    # #sold.map({False:np.nan})
    # sold.iloc[-10:-1,0:20]

    ## Lost

    #the time period that you want to get after the trigger
    time_period20 = [get_period(14400, (row[6]+60000), test) for i,row in trigger_df.iterrows()]

    #did we lose???
    trigger_df['lost'] = pd.DataFrame([did_buy(time_period20[i].low,(row[1]*.10),i) for i,row in trigger_df.iterrows()]).any(axis=1)

    trigger_df['lost'].sum()
    trigger_df.loc[trigger_df['lost']==False,:]

    trigger_df

    trigger_df['close_low'] = trigger_df.close - trigger_df.low
    trigger_df.sort_values(by='day', ascending=False)

    trigger_df.day.value_counts().sort_index()

    profit = (trigger_df['bought'] == True) & (trigger_df['sold'] == True)
    len(trigger_df.loc[profit,:])

    loss = (trigger_df['bought'] == True) & (trigger_df['sold'] == False)
    len(trigger_df.loc[loss,:])
   

    #np.percentile(test['high'],[65])[0]

    #1604415780000
    #sold_time = test.loc[(test['high']>=x[13])&(test['datetime']>=x[6]), :].datetime.head(1).to_numpy()[0]
    #trigger_df['days_taken'] = 
    min_taken = [(test.loc[(test['high']>=x[13])&(test['datetime']>x[6]), ['datetime']].head(1).values[0][0]-x[6])/60000 for i,x in trigger_df.loc[profit|loss,:].iterrows()]
    min_df = trigger_df.drop(trigger_df.loc[trigger_df['bought']==False,:].index)
    min_df['min_taken'] = min_taken
    min_df.dtypes
    min_df.sort_values('min_taken', ascending=False)
    
    
#     print(symbol)
#     print('total sells: {} \ntotal loss: {}'.format(len(trigger_df.loc[profit,:]),len(trigger_df.loc[loss,:])))
#     print('minutes to sell:  ', round(min_df.min_taken.mean(),4))
#     print('                            df of unsold triggers')
    

    
#     trigger_df.loc[loss,:]
    #trigger_df.loc[profit,:]
    sym_data = {
        'symbol':symbol,
        'total_sells':len(trigger_df.loc[profit,:]),
        'total_loss':len(trigger_df.loc[loss,:]),
        'min_to_sell':round(min_df.min_taken.mean(),4),
        'profit': my_profit
    }
    
#     sym = pd.DataFrame(data=sym_data, index=[i])
#     sym.head()
#     c.append(sym, ignore_index=True)
    sym_dict.append(sym_data)
#     print(symbol,i)
trades = pd.DataFrame.from_dict(sym_dict, orient='columns')

trades

In [ ]:
trades.loc[trades['min_to_sell']<6,:].sort_values('min_to_sell').sum()

In [ ]:
trades.loc[trades['min_to_sell']<6,:].sort_values('min_to_sell').count()

In [113]:
trades.sort_values('min_to_sell')

   symbol  total_sells  total_loss  min_to_sell  profit
0    ATVI            3           0       1.0000  1.0002
45    KHC            4           0       1.0000  1.0002
41    SYY            3           0       1.0000  1.0002
36   MDLZ            2           0       1.0000  1.0002
34    HBI            3           0       1.0000  1.0002
33    UAA            1           0       1.0000  1.0002
30    TJX            1           0       1.0000  1.0002
27    PHM            2           0       1.0000  1.0002
25    LVS            3           0       1.0000  1.0002
47    BKR            3           0       1.0000  1.0002
22    LEN            5           0       1.0000  1.0002
21     HD            1           0       1.0000  1.0002
20    GPS            6           1       1.0000  1.0002
19   EBAY            2           0       1.0000  1.0002
16    CCL            6           0       1.0000  1.0002
24     LB            2           0       1.0000  1.0002
49    COP            3           0       1.0000  1.0002
2    LUMN            2           0       1.0000  1.0002
14   FOXA            2           0       1.0000  1.0002
12     FB            3           0       1.0000  1.0002
11  DISCK            1           0       1.0000  1.0002
10   VIAC            1           0       1.0000  1.0002
1   CMCSA            1           0       1.0000  1.0002
42    WBA            6           0       1.1667  1.0002
9   DISCA            6           0       1.1667  1.0002
31   WYNN            3           0       1.3333  1.0002
38     KR            5           0       1.4000  1.0002
7       T            5           0       1.6000  1.0002
44     PM            1           0       2.0000  1.0002
3     DIS            3           0       2.0000  1.0002
46    APA            4           0       2.0000  1.0002
15    BBY            3           0       2.0000  1.0002
4      EA            2           0       2.0000  1.0002
37     KO            4           0       3.7500  1.0002
40     PG            1           0       4.0000  1.0002
39     MO            4           0       5.7500  1.0002
32    MGM            7           0       6.7143  1.0002
6    NFLX            3           0      11.0000  1.0002
28    RCL            4           0      22.5000  1.0002
43    WMT            3           0      23.3333  1.0002
8      VZ            6           0      25.5000  1.0002
29   SBUX            1           0      26.0000  1.0002
26    NKE            1           0      29.0000  1.0002
23    LOW            3           0      60.6667  1.0002
17    TPR            5           0     227.2000  1.0002
18    DHI            3           0     305.0000  1.0002
5     IPG            1           0    1188.0000  1.0002
13   TWTR            0           0          NaN  1.0002
35   ULTA            0           0          NaN  1.0002
48    COG            0           0          NaN  1.0002

In [114]:
trades.total_loss.sum()

1

In [115]:
trades.sum()

symbol         ATVICMCSALUMNDISEAIPGNFLXTVZDISCAVIACDISCKFBTW...
total_sells                                                  144
total_loss                                                     1
min_to_sell                                              1978.08
profit                                                     50.01
dtype: object

In [116]:
trades.min_to_sell.mean()

42.08682978723404

In [117]:
trades.loc[~(trades['min_to_sell']<6),:].mean()

total_sells      2.642857
total_loss       0.000000
min_to_sell    174.992209
profit           1.000200
dtype: float64